# Generated by Django 4.1.13 on 2025-03-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0011_alter_voter_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
