# Generated by Django 5.1.6 on 2025-04-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0012_setpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setpassword',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
