# Generated by Django 5.1.6 on 2025-04-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0013_alter_setpassword_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$XwQOlWX8BIY4aMVitbkw8K$f8R5h/mD3eRTdJQAu4RYQbX7FMoXpqyoTdPC1x9pk/A=', max_length=128),
        ),
    ]
