# Generated by Django 5.1.6 on 2025-04-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0014_voter_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$z9NtnuUgx54NB77firpdHA$cJaRTMYf36J69Emz83Ey5IqkVDHSgKwPBvAhENiUSMg=', max_length=128),
        ),
    ]
