# Generated by Django 5.1.6 on 2025-04-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0015_alter_voter_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$B4aLVouIkqN9X06j2hRWdc$4pjP7jYA+/ibsyAek1PM/fllw8zbkQzKAVdomOUPi9o=', max_length=128),
        ),
    ]
