# Generated by Django 5.1.6 on 2025-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0016_alter_voter_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('representation', models.CharField(max_length=255)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='symbols/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$jDbxQoYywIXyKDgpWvv8zD$i+5NzjkLvf61rsJ06Yt/xksqHvPi/4Ds/XPrWVP+uyA=', max_length=128),
        ),
    ]
