# Generated by Django 5.1.6 on 2025-04-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0017_candidate_alter_voter_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$iowhN8TOrZWbIUZExlDM2u$Nta+rY/XdbboQwt5V/bTAKoRNpwvfXxRvZpc5fJNJ9A=', max_length=128),
        ),
    ]
