# Generated by Django 5.1.6 on 2025-04-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0021_alter_voter_password_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$pMng3BSOqyNxgjPcbAWgy8$9mpsyD42KB2haNqCOVkJseRUoK8wFRqTwJQ3ps9w8vQ=', max_length=128),
        ),
    ]
