# Generated by Django 5.1.6 on 2025-04-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0022_alter_voter_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Wruk43EgZFSoN5lvsMf7Hd$ewRtvjK5oWD4VCWaoyxJiNOfpIlel4mcBwhMDAZJPf8=', max_length=128),
        ),
    ]
