# Generated by Django 5.1.6 on 2025-05-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0024_remove_vote_count_vote_user_alter_voter_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$v2T9FQfcMvv7qcfsfQyia5$5PJeFXWBfNMzQilgyqNcYJrL3JbDHJyTu47AR5UhRmU=', max_length=128),
        ),
    ]
