# Generated by Django 5.1.6 on 2025-05-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0025_alter_voter_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$bATHmPecsOlwPBRuxWU7op$lEBgc2Yy17YOa3Tm2actOwWHxq3sZdoAynAodGYbhfI=', max_length=128),
        ),
    ]
