# Generated by Django 5.1.6 on 2025-05-07 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0026_alter_voter_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myprojectdpoll.voter'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$7nGk4HAYCCqoviUxt14j8M$Fs4bo2KZ59rmZ9Yc1WssoQzyUdl8Xtsx4eQUZbJHZAk=', max_length=128),
        ),
    ]
