# Generated by Django 5.1.6 on 2025-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0027_alter_vote_user_alter_voter_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$W4xRf5cd7PovuyXsQAgK4Q$9oVbsxe7l7g/IfBKfrc+3loR4qo7Dq2FOqVWWc7ylz4=', max_length=128),
        ),
    ]
